#!/bin/bash
set -euo pipefail

usage() {
    cat <<eof >&2
usage: $0

    description
        takes prototypicality_rankings.txt for
        each subject and moves exemplars to
        subj#/exemplars folder, then adjusts
        all RMS to 1, extends vowel length to
        300 ms with Praat and zero-pads to 500
        ms
eof
    exit 1
}

if [[ $# -ne 0 ]]; then
    usage
fi

# clean out old files
rm -rf subj*/modified

echo "Copying files from raw/ to modified/"
for subject_dir in subj*/; do
    echo "$subject_dir"
    mkdir "$subject_dir"/modified
    cp "$subject_dir"/raw/*.wav "$subject_dir"/modified
    chmod 700 "$subject_dir"/modified/*.wav
done

# extend vowel duration
echo "Extending vowel durations"
for file in subj*/modified/*.wav ; do
    echo "$file"
    subject_dir="$(dirname "$file")"
    vowel="$(basename -s .wav "$file")"
    duration="$("$(soxi -D "$file")"*100)"
    if  [ "$duration" -lt 5 ]
    then
        continue
    else
        echo "Skipping $file because it is too short"
        /Applications/Praat.app/Contents/MacOS/Praat --run functions/match_vowel_duration.praat "$subject_dir" "$vowel"
    fi
done

# match rms
echo "Matching rms"
matlab -nodisplay -r "addpath('functions'); run('normalize_stim_rms.m'); quit"

# move top 3 exemplars to a separate folder
#for subject_dir in subj*/ ; do
#    echo "Moving exemplars"
#    echo "$subject_dir"
#    python3 functions/move_exemplars.py "$subject_dir"
#done
